### ISSUE TITLE
A useful link for USPTO dataset

### ISSUE THREAD

**Issue by hanyang-sh** [ChemFoundationModels/ChemLLMBench#2]
https://deepchem.readthedocs.io/en/latest/api_reference/moleculenet.html#uspto-datasets

**Comment by hanyang-sh** [comment]
At the same time, could you explain the meaning of [Suzuki](https://github.com/ChemFoundationModels/ChemLLMBench/blob/main/data/yield_prediction/Suzuki.npz), or tell me where you collect them.

**Comment by taichengguo** [comment]
Thanks for your attention for this project! The suzuki is a  specific type of chemical reaction and we have updated the data source in our README: https://github.com/ChemFoundationModels/ChemLLMBench#dataset

**Comment by hanyang-sh** [comment]
Thanks a lot, I find your paper report the BLEU-2 of MolT6-Large in Molecule Captioning is 0.482, however, it is reported as 0.594 in the original paper.
![image](https://github.com/ChemFoundationModels/ChemLLMBench/assets/31543505/d4c2e0f0-f658-4ef5-9c0b-0f16baf0e3f6)
![image](https://github.com/ChemFoundationModels/ChemLLMBench/assets/31543505/ff67524e-1dc6-47cd-be2a-e046cbbd65c7)

**Comment by taichengguo** [comment]
This is because the test set are different. In the original paper, they use the whole test set to evaluate. In our work, due the API requesting time and money consumption, we sample 100 examples from the test set. The 0.482 here is the result for the 100 examples.

**Comment by hanyang-sh** [comment]
Thanks, I see. 100 samples are a bit small (as ~3300 samples in the test set), this may cause bias, and I also suggest you should indicate that in the paper.

**Comment by hanyang-sh** [comment]
I am confused by the Scaffold and the Random option in the tables, is it mean that Scaffold is the certain examples (carefully picked) and Random is the random examples from the train set?
