### ISSUE TITLE
PubChem data used in the paper

### ISSUE THREAD

**Issue by hzlhzlhzlhzl** [ChemFoundationModels/ChemLLMBench#3]
Hi, thanks for this amazing work. Can you provide the PubChem data used in the paper? Thank you so much.

**Comment by taichengguo** [comment]
Hi! Thanks for your attention to our work. We have uploaded the PubChem data we used: https://github.com/ChemFoundationModels/ChemLLMBench/blob/main/data/name_prediction/pubchem.csv 

Thanks!
