### ISSUE TITLE
Question about the prompt for molecular property prediciton

### ISSUE THREAD

**Issue by bbjy** [ChemFoundationModels/ChemLLMBench#5]
Hi! Thanks for your work!

I have a question about the prompt for molecular property prediction. 

In the Section 4.1 (Tasks with selectively competitive (SC) performance), it said "the prompt includes _inhibit HIV replication or drugs failed clinical trials for toxicity reason_, and we observed a significant decline in the performance of GPT models upon removing property labels from the prompt", but the template for the property prediction in this repository seems not including such detailed information. 

So could you please explain it more detailedly? Thanks a lot!

**Comment by taichengguo** [comment]
Hi! Thanks so much for your attention to our work!

For the code in this repository: The current code we submitted to GitHub is an initial version (with label). We did the experiments (without label) during the NeurIPS rebuttal phase, so we haven't submitted the prompt template for this case (without label) to Github. 

For the Label interpretation: More details are in the Appendix of our paper on Page 18.

<img width="554" alt="截屏2023-12-29 下午5 18 29" src="https://github.com/ChemFoundationModels/ChemLLMBench/assets/124655542/613e3adf-88b9-4e84-bb53-9df11c135258">

Thanks!

**Comment by Data-reindeer** [comment]
Hi, Taicheng
Thank you for bringing this work to the community! However, a friendly reminder that some of the current prompts for Propert Prediction (PP) datasets are not matched correctly. For example, the prompts for HIV and Clintox seems to be swapped.

**Comment by taichengguo** [comment]
Thanks for your kind reminder! @KehanGuo2  Could you fix the prompts for the property prediction?

**Comment by KehanGuo2** [comment]
thanks for the reminder, we have fixed the issue now.
