### ISSUE TITLE
question about pipeline code &dataset

### ISSUE THREAD

**Issue by evergreen-bupt** [ChemFoundationModels/ChemLLMBench#8]
Hello, I am trying to test the performance of my model on chemllmbench, but I meet some issues as following: 
1. For property prediction tasks, there is a lack of code for calculating the AUC-ROC metric.
2. For  Name Prediction task, it seems that the previous dataset download location has become invalid. 
Could you help me resolve these issues?

**Comment by taichengguo** [comment]
2. For Name Prediction task, the download link is updated and valid.

**Comment by taichengguo** [comment]
1. For property prediction tasks, @KehanGuo2 can you help fix this issue?

**Comment by KehanGuo2** [comment]
With the "generated_p", which is "Yes"/"No", you can easily calculate the AUROC score
